spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linea_produccion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: linea_user
    password: linea_pass
  jpa:
    hibernate:
      ddl-auto: update   # en dev -> update; en prod usar flyway/liquibase
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080